SearchSystem/Controllers/SearchController.cs
using SearchSystem.Data;
using SearchSystem.Data.Repository;
using SearchSystem.Entities;
using SearchSystem.Models;
using SearchSystem.Models.Constants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SearchSystem.Controllers
{

    public class SearchController : Controller
    {
        private UnitOfWork _db;

        public SearchController()
        {
            this._db = new UnitOfWork();
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowKeywords(string departmentName)
        {
            ViewBag.departmentName = departmentName;

            int departmentId = this._db.DepartmentRepository.GetDepartmentIdByName(departmentName);
            IEnumerable<Keyword> keywords = this._db.KeywordRepository.GetAllKeywordsFromDepartment(departmentId);

            return View(keywords);
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "SearchProfessors")]
        public ActionResult SearchProfessors(IEnumerable<int> checkboxList, string departmentName)
        {
            if (checkboxList != null)
            {
                ViewBag.Error = false;
                IEnumerable<Professor> professors = this._db.ProfessorRepository.GetAllProfessorsWithKeywordsFromDepartment(departmentName);//Get all professors from selected department
                
                //Make array for all professors with their ranks
                int professorsCount = professors.Count();
                if (professorsCount > 0)
                {
                    ProfessorRankModel[] ProfessorsRanks = new ProfessorRankModel[professorsCount];
                    for (int i = 0; i < ProfessorsRanks.Length; i++)
                    {
                        ProfessorsRanks[i] = new ProfessorRankModel();
                    }

                    int currentProfessor = 0;
                    int fullMatch = 0; //full match between user keyword and professor keyword
                    int diferentFromZero = 0;//full match or with same node
                    double professorRank = 0.0f;

                    IQueryable<KeywordBasicModel> userKeywords = this._db.KeywordRepository.GetUserKeywordsAndFields(checkboxList.ToList<int>());//Get keywords from UserKeywords

                    foreach (Professor professor in professors)
                    {
                        foreach (Keyword professorKeyword in professor.Keywords)
                        {
                            //foreach every keywords from user
                            foreach (KeywordBasicModel userKeyword in userKeywords)
                            {
                                //compare if they are equal (if compare return 0 they are equal)
                                if (string.Compare(professorKeyword.Value, userKeyword.Value) == 0)
                                {
                                    professorRank += 1.0f;
                                    fullMatch++;
                                    diferentFromZero++;
                                }
                                //compare if they have same node
                                else if (professorKeyword.FieldId == userKeyword.FieldId)
                                {
                                    professorRank += 0.5f;
                                    diferentFromZero++;
                                }
                                //if they dont equal and they dont have same node
                                else
                                {
                                    professorRank += 0.0f;
                                }
                            }
                        }

                        if (fullMatch == userKeywords.Count() || fullMatch == professor.Keywords.Count)
                        {
                            professorRank = 1.0f * 100;
                            ProfessorsRanks[currentProfessor].Rank = professorRank;
                            ProfessorsRanks[currentProfessor].ProfessorId = professor.ProfessorId;
                            ProfessorsRanks[currentProfessor].FirstName = professor.FirstName;
                            ProfessorsRanks[currentProfessor].LastName = professor.LastName;
                            ProfessorsRanks[currentProfessor].Subjects = professor.Subjects;
                        }
                        else
                        {
                            professorRank = Math.Round((professorRank / diferentFromZero) * 100, 2);
                            ProfessorsRanks[currentProfessor].Rank = professorRank;
                            ProfessorsRanks[currentProfessor].ProfessorId = professor.ProfessorId;
                            ProfessorsRanks[currentProfessor].FirstName = professor.FirstName;
                            ProfessorsRanks[currentProfessor].LastName = professor.LastName;
                            ProfessorsRanks[currentProfessor].Subjects = professor.Subjects;
                        }

                        //For every professor
                        fullMatch = 0;
                        professorRank = 0.0f;
                        diferentFromZero = 0;
                        currentProfessor++;
                    }
                    IEnumerable<ProfessorRankModel> sorted = ProfessorsRanks
                        .Where(r => double.IsNaN(r.Rank) == false)
                        .OrderByDescending(o => o.Rank)
                        .Take(ProfessorConstraints.FIRST_N_PROFESSORS);

                    return View(sorted);
                }
            }
            ViewBag.Error = true;
            return View();
        }

        [HttpPost]
        [MultipleButton(Name = "action", Argument = "SearchThesеs")]
        public ActionResult SearchThesеs(IEnumerable<int> checkboxList, string departmentName, string type, string complexity, string status)
        {
            if (checkboxList!=null)
            {
                string defaultString = "Всички";
                ViewBag.Error = false;
                ViewBag.typeFilterApplied = !type.Equals(defaultString);
                ViewBag.complexityFilterApplied = !complexity.Equals(defaultString);
                ViewBag.statusFilterApplied = !status.Equals(defaultString);

                List<Thesis> theses = this._db.ThesisRepository
                    .GetAllThesesWithKeywordsFromDepartment(departmentName)
                    .Where(thesis => ((ViewBag.typeFilterApplied == true) ? thesis.Type.Equals(type) : true) &&
                                     ((ViewBag.complexityFilterApplied == true) ? thesis.Complexity.Equals(complexity) : true) &&
                                     ((ViewBag.statusFilterApplied == true) ? thesis.Status.Equals(status) : true))
                    .ToList<Thesis>();

                //Make array for all thesis with their ranks
                int thesesCount = theses.Count();
                if (thesesCount > 0)
                {
                    ThesisRankModel[] ThesesRanks = new ThesisRankModel[thesesCount];
                    for (int i = 0; i < ThesesRanks.Length; i++)
                    {
                        ThesesRanks[i] = new ThesisRankModel();
                    }

                    int currentThesis = 0;
                    int fullMatch = 0; //full match between user keyword and thesis keyword
                    int diferentFromZero = 0;//full match or with same node
                    double thesisRank = 0.0f;

                    IQueryable<KeywordBasicModel> userKeywords = this._db.KeywordRepository.GetUserKeywordsAndFields(checkboxList.ToList<int>());//Get keywords from UserKeywords

                    foreach (Thesis thesis in theses)
                    {
                        foreach (Keyword thesisKeyword in thesis.Keywords)
                        {
                            //foreach every keywords from user
                            foreach (KeywordBasicModel userKeyword in userKeywords)
                            {
                                //compare if they are equal (if compare return 0 they are equal)
                                if (string.Compare(thesisKeyword.Value, userKeyword.Value) == 0)
                                {
                                    thesisRank += 1.0f;
                                    fullMatch++;
                                    diferentFromZero++;
                                }
                                //compare if they have same node
                                else if (thesisKeyword.FieldId == userKeyword.FieldId)
                                {
                                    thesisRank += 0.5f;
                                    diferentFromZero++;
                                }
                                //if they dont equal and they dont have same node
                                else
                                {
                                    thesisRank += 0.0f;
                                }
                            }
                        }

                        if (fullMatch == userKeywords.Count() || fullMatch == thesis.Keywords.Count)
                        {
                            thesisRank = 1.0f * 100;
                            ThesesRanks[currentThesis].Rank = thesisRank;
                            ThesesRanks[currentThesis].ThesisId = thesis.ThesisId;
                            ThesesRanks[currentThesis].ThesisTitle = thesis.ThesisTitle;
                            ThesesRanks[currentThesis].ThesisDescription = thesis.ThesisDescription;
                            ThesesRanks[currentThesis].Status = thesis.Status;
                            ThesesRanks[currentThesis].Type = thesis.Type;
                            ThesesRanks[currentThesis].Complexity = thesis.Complexity;

SearchSystem/Controllers/ThesisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SearchSystem.Models;
using SearchSystem.Data;
using SearchSystem.Entities;
using SearchSystem.Models.Constants;
using System.Collections;

namespace SearchSystem.Controllers
{

    public class ThesisController : Controller
    {
        private UnitOfWork _db;

        public ThesisController()
        {
            this._db = new UnitOfWork();
        }

        public ActionResult Index(int currentId, string type)
        {
            Thesis thesis = this._db.ThesisRepository.GetThesisByID(currentId);

            if(thesis==null)
            {
                if (type == "Next")
                {
                    int nextThesisId = this._db.ThesisRepository.NextOrFirstThesis(currentId);//Return next or first
                    return RedirectToAction("Index", new { currentId = nextThesisId, type = "Next"});
                }
                else
                {
                    int previousThesisId = this._db.ThesisRepository.PreviousOrLastThesis(currentId);//return previous or last
                    return RedirectToAction("Index", new { currentId = previousThesisId, type = "Previous" });
                }
            }

            return View(thesis);
        }
        
        public ActionResult SearchReviewers(int thesisId, int professorId)
        {
            //Get current thesis
            Thesis thesis = this._db.ThesisRepository.GetThesisByID(thesisId);

            //Get all professors from thesis department
            IEnumerable<Professor> professors = this._db.ProfessorRepository.GetAllProfessorsWithKeywordsFromDepartment(thesis.Professor.DepartmentName);
            
            //Make array for all professors from thesis department
            ProfessorRankModel[] ProfessorsRanks = new ProfessorRankModel[professors.Count()];
            for (int i = 0; i < ProfessorsRanks.Length; i++)
            {
                ProfessorsRanks[i] = new ProfessorRankModel();
            }

            int currentProfessor = 0;
            int fullMatch = 0; //full match between user keyword and professor keyword
            int diferentFromZero = 0;//full match or with same node
            double professorRank = 0.0f;

            foreach (Professor professor in professors)
            {
                foreach (Keyword professorKeyword in professor.Keywords)
                {
                    //foreach every keywords from thesis
                    foreach (Keyword thesisKeyword in thesis.Keywords)
                    {
                        //compare if they are equal (if compare return 0 they are equal)
                        if (string.Compare(professorKeyword.Value, thesisKeyword.Value) == 0)
                        {
                            professorRank += 1.0f;
                            fullMatch++;
                            diferentFromZero++;
                        }
                        //compare if they have same node
                        else if (professorKeyword.FieldId == thesisKeyword.FieldId)
                        {
                            professorRank += 0.5f;
                            diferentFromZero++;
                        }
                        //if they dont equal and they dont have same node
                        else
                        {
                            professorRank += 0.0f;
                        }
                    }
                }

                if (fullMatch == thesis.Keywords.Count() || fullMatch == professor.Keywords.Count)
                {
                    professorRank = 1.0f * 100;
                    ProfessorsRanks[currentProfessor].Rank = professorRank;
                    ProfessorsRanks[currentProfessor].ProfessorId = professor.ProfessorId;
                    ProfessorsRanks[currentProfessor].FirstName = professor.FirstName;
                    ProfessorsRanks[currentProfessor].LastName = professor.LastName;
                    ProfessorsRanks[currentProfessor].Subjects = professor.Subjects;
                }
                else
                {
                    professorRank = Math.Round((professorRank / diferentFromZero) * 100, 2); 
                    ProfessorsRanks[currentProfessor].Rank = professorRank;
                    ProfessorsRanks[currentProfessor].ProfessorId = professor.ProfessorId;
                    ProfessorsRanks[currentProfessor].FirstName = professor.FirstName;
                    ProfessorsRanks[currentProfessor].LastName = professor.LastName;
                    ProfessorsRanks[currentProfessor].Subjects = professor.Subjects;
                }

                //For every professor
                fullMatch = 0;
                professorRank = 0.0f;
                diferentFromZero = 0;
                currentProfessor++;
            }

            IEnumerable<ProfessorRankModel> sorted = ProfessorsRanks
                .OrderByDescending(o => o.Rank)
                .Where(i => i.ProfessorId != professorId)
                .Where(r => double.IsNaN(r.Rank) == false)
                .Take(ProfessorConstraints.FIRST_N_PROFESSORS);

            ViewBag.ID = thesisId;
            return View(sorted);
        }
        
        public ActionResult ThesesFromDepartmentByQuery(string departmentName, string status, string type)
        {
            IEnumerable<Thesis> theses = this._db.ThesisRepository.GetAllThesesFromDepartmentByStatusAndType(departmentName, status, type);
            return View("~/Views/Shared/_ThesesListPartial.cshtml", theses);
        }

        [HttpGet]
        public ActionResult SearchThesesByQueryString(string queryString)
        {
            IEnumerable<Thesis> theses = this._db.ThesisRepository.SearchThesesByQueryString(queryString);
            return View("~/Views/Shared/_ThesesListPartial.cshtml", theses);
        }
	}
}

SearchSystem/Views/Shared/_DepartmentsPartial.cshtml
<!--Use in CustomRegistration->ChooseDepartment, Search->Index, Professor->Index, Thesis->Index -->

@Html.DropDownList(
    "departmentName", 
    new List<SelectListItem> 
    { 
        new SelectListItem { Text = "Компютърни Системи и Технологии", Value = "Компютърни Системи и Технологии"}, 
    })

SearchSystem/Views/Shared/_KeywordsPartial.cshtml
<!--Use in Search->ShowKeywords, ProfessorProfile->CreateThesis, CustomRegistration->RegisterProfessor-->
<!--Use in ProfessorProfile->EditProfessorKeywords, ProfessorProfile->EditThesisKeywords-->
@model IList<SearchSystem.Entities.Keyword>
@Styles.Render("~/Content/UniversitySystem.css")
@Scripts.Render("~/bundles/jquery")

@{int InRow = Model.Count() / 3;}
<div>
    <h3 style="color:orange">Моля изберете ключови думи</h3>
    <div class="keywords-row">
        @for (int i = 0; i < Model.Count(); i++)
        {
            bool renderRow = i == InRow || i == (2 * InRow) ? true : false;

            if (renderRow)
            {
                @:</div>
                @:<div class="keywords-row">
            }

            <input type="checkbox" id="@Model[i].KeywordId" name="checkboxList" value="@Model[i].KeywordId" class="chkbox">
            <label style="height:40px; width:250px;" for="@Model[i].KeywordId" @{if (i % 2 == 0) { <text> class="odd" </text>   }}> 
            
                @if (Model[i].Field.ParentField == null)
                {
                    <span class="glyphicon glyphicon-chevron-down"></span> @Model[i].Value
                }

                else {@Model[i].Value  }

            </label>
        }
   </div>
</div>


<script>
    $(document).ready(function () {
        $(".chkbox").click(function () {
            if ($(this).is(":checked")) {
                $('label[for=' + $(this).val() + ']').addClass("checked");
            }
            else {
                $('label[for=' + $(this).val() + ']').removeClass("checked");
            }
        });
    });
</script>

@if(@ViewBag.SelectedKeywords != null){
    <!--This is selected keywords-->
    foreach (var keywordId in (IEnumerable<int>)@ViewBag.SelectedKeywords)
    {
        <p class="hidden">@keywordId</p>
    }
    <!--We make keywords who already have: checked-->
    <script>
        $(".hidden").each(function (index, element) {
            var el = $(element);
            $('label[for=' + el.html() + ']').trigger("click").addClass("checked");
        });
    </script>
}

SearchSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title University System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300italic,400italic,500italic' rel='stylesheet' type='text/css'>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              <p class="glyphicon glyphicon-leaf white-glyphicon"></p>@Html.ActionLink("University System", "Index", "Home", null, new { @class = "navbar-brand", @style = "color:#F8F8F8; font-family:Comic Sans; " })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Начало", "Index", "Home")</li>
                    <li>@Html.ActionLink("Търсене", "Index", "Search")</li>
                    <li>@Html.ActionLink("Преподаватели", "Index", "Professor", new { currentId = 1, type = "Next" }, null)</li>
                    <li>@Html.ActionLink("Теми", "Index", "Thesis", new { currentId = 1, type = "Next" }, null)</li>
                    <li>@Html.ActionLink("Помощ", "About", "Home")</li>
                    <!--<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Университет<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Преподаватели", "Index", "Professor", new { currentId = 1, type = "Next" }, null)</li>
                            <li>@Html.ActionLink("Теми", "Index", "Thesis", new { currentId = 1, type = "Next" }, null)</li>
                        </ul>
                    </li>-->
                    @if(User.IsInRole("Professor")){
                        <li>@Html.ActionLink("Профил", "ProfessorProfile", "ProfessorProfile")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="push"><footer class="footer">
    <p>&copy; @DateTime.Now.Year - Design by <b><a href="https://www.linkedin.com/in/trifondardzhonov">Eng. Trifon Dardzhonov</a></b> and <b>Prof. Dr. Veselka Boeva, PhD.</b></p>
</footer></div>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SearchSystem/Views/Shared/_ProfessorsListPartial.cshtml
<!--Use int Professor->ProfessorFromDepartment-->
@model IEnumerable<SearchSystem.Entities.Professor>

<table class="table">
    <tr>
        <th class="label-info th-small-info">Име</th>
        <th class="label-info th-small-info">Фамилия</th>
        <th class="label-info">Водени дисциплини</th>
        <th class="label-info">Образование</th>
        <th class="label-info">Професионални интереси</th>
        <th class="label-info th-small-info">Описание</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subjects)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Education)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProfesionalInterests)
            </td>
            <td>
                @Html.ActionLink("Пълно описание", "Index", "Professor", new { currentId = item.ProfessorId, type = "Current" }, null)
            </td>
        </tr>
    }
</table>

SearchSystem/Views/Shared/_SearchProfessorsListPartial.cshtml
<!--Use in search professors and search reviewers-->
@model IEnumerable<SearchSystem.Models.ProfessorRankModel>

<table class="table">
    <tr>
        <th class="label-success th-small-info">Име</th>
        <th class="label-success th-small-info">Фамилия</th>
        <th class="label-success">Водени дисциплини</th>
        <th class="label-success th-small-info">Подобие</th>
        <th class="label-success th-small-info">Описание</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td style="text-align:justify;">
                @Html.DisplayFor(modelItem => item.Subjects)
            </td>
            <td style="text-align:center;">
                <strong>@Html.DisplayFor(modelItem => item.Rank)%</strong>
            </td>
            <td>
                @Html.ActionLink("Пълно описание", "Index", "Professor", new { currentId = item.ProfessorId, type = "Current" }, null)
            </td>
        </tr>
    }
</table>

SearchSystem/Views/Shared/_ThesesListPartial.cshtml
<!--Use in Thesis->ThesesFromDeaprtment, Professor->Index-->
@model IEnumerable<SearchSystem.Entities.Thesis>

<table class="table">
    <tr>
        <th class="label-info">Заглавие</th>
        <th class="label-info">Описание</th>
        <th class="label-info th-small-info">Преподавател</th>
        <th class="label-info th-small-info">Заетост</th>
        <th class="label-info th-small-info">Тип</th>
        <th class="label-info th-small-info">Сложност</th>
        <th class="label-info th-small-info">Описание</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align:justify;">
                @Html.DisplayFor(modelItem => item.ThesisTitle)
            </td>
            <td style="text-align:justify;"
                id="description-@item.ThesisId">
                @(item.ThesisDescription.Length > 250 ? item.ThesisDescription.Substring(0, 250) + "..." : item.ThesisDescription)
                @Ajax.ActionLink("Виж пълно описание", "GetThesisDescription", "Professor",
                                        new { thesisId = item.ThesisId },
                                        new AjaxOptions
                                        {
                                            HttpMethod = "Get",
                                            InsertionMode = InsertionMode.Replace,
                                            UpdateTargetId = "description-" + item.ThesisId
                                        })
            </td>
            <td style="text-align:center;">
                @Html.DisplayFor(modelItem => item.Professor.FirstName) 
                @Html.DisplayFor(modelItem => item.Professor.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Complexity)
            </td>
            <td>
                @Html.ActionLink("Към темата", "Index", "Thesis", new { currentId = item.ThesisId, type = "Current" }, null)
            </td>
        </tr>
    }
</table>