SearchSystem/Models/BaseViewModels/ThesisViewModel.cs
using SearchSystem.Validators;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SearchSystem.Models.BaseViewModels
{
    [FluentValidation.Attributes.Validator(typeof(ThesisViewModelValidator))]
    public class ThesisViewModel
    {

        public ThesisViewModel()
        {
            this.АwardedOn = DateTime.Now;
        }

        public int ThesisId { get; set; }

        [Display(Name = "Име на темата")]
        [DataType(DataType.MultilineText)]
        public string ThesisTitle { get; set; }

        [Display(Name = "Описание")]
        [DataType(DataType.MultilineText)]
        public string ThesisDescription { get; set; }

        [Display(Name = "Публикувана в системата")]
        public DateTime CreatedOn { get; set; }

        [Display(Name = "Заетост")]
        public string Status { get; set; }

        [Display(Name = "Тип")]
        public string Type { get; set; }

        [Display(Name = "Сложност")]
        public string Complexity { get; set; }

        [Display(Name = "Име и Фамилия (студент)")]
        public string StudentName { get; set; }

        [Display(Name = "Факултетен номер (студент)")]
        public long StudentFakNo { get; set; }

        [Display(Name = "Име и Фамилия (рецензент)")]
        public string ReviewerName { get; set; }

        [Display(Name = "Защитена на")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime АwardedOn { get; set; }

        public int ProfessorId { get; set; }
    }
}

SearchSystem/Controllers/ProfessorController.cs
using SearchSystem.Data;
using SearchSystem.Entities;
using SearchSystem.Models;
using SearchSystem.Models.BaseViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SearchSystem.Controllers
{
    public class ProfessorController : Controller
    {
        private UnitOfWork _db;

        public ProfessorController()
        {
            this._db = new UnitOfWork();
        }

        [HttpGet]
        public ActionResult Index(int currentId, string type)
        {
            Professor professor = this._db.ProfessorRepository.GetProfessorById(currentId);

            if(professor==null)
            {
                if (type == "Next")
                {
                    int nextProfessorId = this._db.ProfessorRepository.NextOrFirstProfessor(currentId);
                    return RedirectToAction("Index", new { currentId = nextProfessorId, type = "Next" });
                }
                else
                {
                    int previousProfessorId = this._db.ProfessorRepository.PreviousOrLastProfessor(currentId);
                    return RedirectToAction("Index", new { currentId = previousProfessorId, type = "Previous" });
                }
            }
            return View(professor);
        }

        public ActionResult GetThesisDescription(int thesisId)
        {
            string fullThesisDescription = this._db.ThesisRepository.GetThesisDescription(thesisId);
            return Content(fullThesisDescription);
        }

        public ActionResult ProfessorsFromDepartment(string departmentName)
        {
            IQueryable<Professor> professors = this._db.ProfessorRepository.GetAllProfessorsWithKeywordsFromDepartment(departmentName);
            return View("~/Views/Shared/_ProfessorsListPartial.cshtml", professors);
        }

        [HttpGet]
        public ActionResult SearchProfessorsByQueryString(string queryString)
        {
            IEnumerable<Professor> professors = this._db.ProfessorRepository.SearchProfessorsByQueryString(queryString);
            return View("~/Views/Shared/_ProfessorsListPartial.cshtml", professors);
        }

	}
}

SearchSystem/Controllers/ThesisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SearchSystem.Models;
using SearchSystem.Data;
using SearchSystem.Entities;
using SearchSystem.Models.Constants;
using System.Collections;

namespace SearchSystem.Controllers
{

    public class ThesisController : Controller
    {
        private UnitOfWork _db;

        public ThesisController()
        {
            this._db = new UnitOfWork();
        }

        public ActionResult Index(int currentId, string type)
        {
            Thesis thesis = this._db.ThesisRepository.GetThesisByID(currentId);

            if(thesis==null)
            {
                if (type == "Next")
                {
                    int nextThesisId = this._db.ThesisRepository.NextOrFirstThesis(currentId);//Return next or first
                    return RedirectToAction("Index", new { currentId = nextThesisId, type = "Next"});
                }
                else
                {
                    int previousThesisId = this._db.ThesisRepository.PreviousOrLastThesis(currentId);//return previous or last
                    return RedirectToAction("Index", new { currentId = previousThesisId, type = "Previous" });
                }
            }

            return View(thesis);
        }
        
        public ActionResult SearchReviewers(int thesisId, int professorId)
        {
            //Get current thesis
            Thesis thesis = this._db.ThesisRepository.GetThesisByID(thesisId);

            //Get all professors from thesis department
            IEnumerable<Professor> professors = this._db.ProfessorRepository.GetAllProfessorsWithKeywordsFromDepartment(thesis.Professor.DepartmentName);
            
            //Make array for all professors from thesis department
            ProfessorRankModel[] ProfessorsRanks = new ProfessorRankModel[professors.Count()];
            for (int i = 0; i < ProfessorsRanks.Length; i++)
            {
                ProfessorsRanks[i] = new ProfessorRankModel();
            }

            int currentProfessor = 0;
            int fullMatch = 0; //full match between user keyword and professor keyword
            int diferentFromZero = 0;//full match or with same node
            double professorRank = 0.0f;

            foreach (Professor professor in professors)
            {
                foreach (Keyword professorKeyword in professor.Keywords)
                {
                    //foreach every keywords from thesis
                    foreach (Keyword thesisKeyword in thesis.Keywords)
                    {
                        //compare if they are equal (if compare return 0 they are equal)
                        if (string.Compare(professorKeyword.Value, thesisKeyword.Value) == 0)
                        {
                            professorRank += 1.0f;
                            fullMatch++;
                            diferentFromZero++;
                        }
                        //compare if they have same node
                        else if (professorKeyword.FieldId == thesisKeyword.FieldId)
                        {
                            professorRank += 0.5f;
                            diferentFromZero++;
                        }
                        //if they dont equal and they dont have same node
                        else
                        {
                            professorRank += 0.0f;
                        }
                    }
                }

                if (fullMatch == thesis.Keywords.Count() || fullMatch == professor.Keywords.Count)
                {
                    professorRank = 1.0f * 100;
                    ProfessorsRanks[currentProfessor].Rank = professorRank;
                    ProfessorsRanks[currentProfessor].ProfessorId = professor.ProfessorId;
                    ProfessorsRanks[currentProfessor].FirstName = professor.FirstName;
                    ProfessorsRanks[currentProfessor].LastName = professor.LastName;
                    ProfessorsRanks[currentProfessor].Subjects = professor.Subjects;
                }
                else
                {
                    professorRank = Math.Round((professorRank / diferentFromZero) * 100, 2); 
                    ProfessorsRanks[currentProfessor].Rank = professorRank;
                    ProfessorsRanks[currentProfessor].ProfessorId = professor.ProfessorId;
                    ProfessorsRanks[currentProfessor].FirstName = professor.FirstName;
                    ProfessorsRanks[currentProfessor].LastName = professor.LastName;
                    ProfessorsRanks[currentProfessor].Subjects = professor.Subjects;
                }

                //For every professor
                fullMatch = 0;
                professorRank = 0.0f;
                diferentFromZero = 0;
                currentProfessor++;
            }

            IEnumerable<ProfessorRankModel> sorted = ProfessorsRanks
                .OrderByDescending(o => o.Rank)
                .Where(i => i.ProfessorId != professorId)
                .Where(r => double.IsNaN(r.Rank) == false)
                .Take(ProfessorConstraints.FIRST_N_PROFESSORS);

            ViewBag.ID = thesisId;
            return View(sorted);
        }
        
        public ActionResult ThesesFromDepartmentByQuery(string departmentName, string status, string type)
        {
            IEnumerable<Thesis> theses = this._db.ThesisRepository.GetAllThesesFromDepartmentByStatusAndType(departmentName, status, type);
            return View("~/Views/Shared/_ThesesListPartial.cshtml", theses);
        }

        [HttpGet]
        public ActionResult SearchThesesByQueryString(string queryString)
        {
            IEnumerable<Thesis> theses = this._db.ThesisRepository.SearchThesesByQueryString(queryString);
            return View("~/Views/Shared/_ThesesListPartial.cshtml", theses);
        }
	}
}

SearchSystem/Views/Thesis/Index.cshtml
@model SearchSystem.Entities.Thesis

@Scripts.Render("~/bundles/jquery")
@Styles.Render("~/Content/UniversitySystem.css")



<div style="padding:10px;" class="col-md-12">
    @using (Html.BeginForm("SearchThesesByQueryString", "Thesis", FormMethod.Get))
    {
        <div class="col-md-12">
            <label for="queryString">
                Търсете теми по:
                <i>име на темата, тип, сложност, описание, име на студент, име на рецензент или име на преподавател.</i>
                <br />
                Резултат:
                <i>Всички теми които съдържат в себе си резултата от вашето търсене в някое от гореспоменатите полета.</i>
            </label>
        </div>
        <div class="col-md-12">
            <input style="max-width:100%; margin-bottom:5px;"
                   class="col-md-12"
                   type="text"
                   id="queryString"
                   name="queryString"
                   placeholder="Въведете вашите критерии" />
            <input type="submit"
                   value="Намери"
                   class="btn btn-info" />
        </div>
    }
</div>
<div class="col-md-12">
    @Html.ActionLink("Предишна", "Index", "Thesis", new { currentId = Model.ThesisId - 1, type = "Previous" }, new { @class = "prev" })
    @Html.ActionLink("Следваща", "Index", "Thesis", new { currentId = Model.ThesisId + 1, type = "Next" }, new { @class = "next pull-right" })<br />
</div>
<table class="table">
    <tr>
        <th class="label-info">@Html.DisplayNameFor(x => x.ThesisTitle)</th>
        <td>@Html.DisplayFor(x => x.ThesisTitle)</td>
    </tr>
    <tr>
        <th class="label-info">@Html.DisplayNameFor(x => x.ThesisDescription)</th>
        <td>@Html.DisplayFor(x => x.ThesisDescription)</td>
    </tr>
    <tr>
        <th class="label-info">@Html.DisplayNameFor(x => x.CreatedOn)</th>
        <td>@Html.DisplayFor(x => x.CreatedOn)</td>
    </tr>
    <tr>
        <th class="label-info">@Html.DisplayNameFor(x => x.Professor.DepartmentName)</th>
        <td>@Html.DisplayFor(x => x.Professor.DepartmentName)</td>
    </tr>
    <tr>
        <th class="label-info">Преподавател</th>
        <td>@Html.DisplayFor(x => x.Professor.FirstName) 
            @Html.DisplayFor(x => x.Professor.LastName) - 
            @Html.ActionLink("Пълно описание", "Index", "Professor", new { currentId = Model.Professor.ProfessorId, type = "Current" }, null)</td>
    </tr>
    <tr>
        <th class="label-info">@Html.DisplayNameFor(x => x.Type)</th>
        <td>@Html.DisplayFor(x => x.Type)</td>
    </tr>
    <tr>
        <th class="label-info">@Html.DisplayNameFor(x => x.Complexity)</th>
        <td>@Html.DisplayFor(x => x.Complexity)</td>
    </tr>
    @if (!Model.Status.Equals("Свободна")) 
    { 
        <tr>
            <th class="label-danger">@Html.DisplayNameFor(x => x.Status)</th>
            <td>@Html.DisplayFor(x => x.Status)</td>
        </tr>
        <tr>
            <th class="label-default">@Html.DisplayNameFor(x => x.StudentName)</th>
            <td>@Html.DisplayFor(x => x.StudentName)</td>
        </tr>
        <tr>
            <th class="label-default">@Html.DisplayNameFor(x => x.StudentFakNo)</th>
            <td>@Html.DisplayFor(x => x.StudentFakNo)</td>
        </tr>
        <tr>
            <th class="label-default">@Html.DisplayNameFor(x => x.ReviewerName)</th>
            <td>@Html.DisplayFor(x => x.ReviewerName)</td>
        </tr>
        if(Model.Status.Equals("Защитена"))
        {
            <tr>
                <th class="label-default">@Html.DisplayNameFor(x => x.АwardedOn)</th>
                <td>@Html.ValueFor(x => x.АwardedOn, "{0:dd MMMM yyyy}")</td>
            </tr>
        }
    }
    else
    {
        <tr>
            <th class="label-success">@Html.DisplayNameFor(x => x.Status)</th>
            <td>@Html.DisplayFor(x => x.Status)</td>
        </tr>
    }
    <tr>
        <th class="label-info">Рецензент</th>
        <td>@Html.ActionLink("Намери", "SearchReviewers", "Thesis", new { thesisId = Model.ThesisId, professorId = Model.Professor.ProfessorId }, null)</td>
    </tr>
</table>

SearchSystem/Views/Thesis/SearchReviewers.cshtml
@model IEnumerable<SearchSystem.Models.ProfessorRankModel>

@Html.Partial("~/Views/Shared/_SearchProfessorsListPartial.cshtml", Model)

@Html.ActionLink("Назад към темата", "Index", "Thesis", new { currentId = @ViewBag.ID, type = "Current" }, null)