SearchSystem/Models/CustomRegistration/ProfessorWithKeywordsViewModel.cs
using SearchSystem.Entities;
using SearchSystem.Models.BaseViewModels;
using SearchSystem.Validators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SearchSystem.Models
{
    public class ProfessorWithKeywordsViewModel
    {
        public ProfessorWithKeywordsViewModel()
        {
            this.Professor = new ProfessorViewModel();
            this.Keywords = new List<Keyword>();
            this.CheckboxList = new List<int>();
        }

        public ProfessorViewModel Professor { get; set; }
        public IList<Keyword> Keywords { get; set; }
        public IEnumerable<int> CheckboxList { get; set; }
    }
}

SearchSystem/Controllers/CustomRegistrationController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using SearchSystem.Data;
using SearchSystem.Entities;
using SearchSystem.Models;
using SearchSystem.Models.BaseViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SearchSystem.Controllers
{
    [Authorize]
    public class CustomRegistrationController : Controller
    {
        private UnitOfWork _db;

        public CustomRegistrationController()
        {
            this._db = new UnitOfWork();
        }

        public ActionResult Index()
        {
            return View();
        }

        //Choose from witch department is logged professor
        public ActionResult ChooseDepartment()
        {
            return View();
        }

        [HttpGet]
        public ActionResult RegisterProfessor(string departmentName)
        {
            HttpContext.Session.Add("departmentId", this._db.DepartmentRepository.GetDepartmentIdByName(departmentName));
            ViewBag.departmentName = departmentName;//TO put it in professor

            ProfessorWithKeywordsViewModel professor = new ProfessorWithKeywordsViewModel();
            professor.Keywords = this._db.KeywordRepository.GetAllKeywordsFromDepartment((int)HttpContext.Session["departmentId"]);

            return View(professor);
        }

        [HttpPost]
        public ActionResult RegisterProfessor(ProfessorWithKeywordsViewModel model)
        {
            if (ModelState.IsValid && model.CheckboxList.Count() > 0)
            {
                Professor professor = model.Professor.ConvertToNewProfessor(User.Identity.GetUserId());
                this._db.ProfessorRepository.Add(professor);
                this._db.ProfessorRepository.SaveChanges();

                //After we create new professor we get him and add keywords to his profile
                this._db.ProfessorRepository.AddKWToProfessor((Professor)this._db.ProfessorRepository.GetProfessorByUserId(User.Identity.GetUserId()), model.CheckboxList);

                //Add role 'Professor' to professors
                var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>());
                roleManager.Create(new IdentityRole("Professor"));
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new DataContext()));
                userManager.AddToRole(User.Identity.GetUserId(), "Professor");

                return RedirectToAction("ProfessorProfile", "ProfessorProfile");
            }
            model.Keywords = this._db.KeywordRepository.GetAllKeywordsFromDepartment((int)HttpContext.Session["departmentId"]);
            ViewBag.SelectedKeywords = model.CheckboxList;
            ViewBag.departmentName = model.Professor.DepartmentName;
        
            return View(model);
        }
	}
}

SearchSystem/Views/CustomRegistration/ChooseDepartment.cshtml
@using (Html.BeginForm("RegisterProfessor", "CustomRegistration", FormMethod.Get))
{ 
    <h3 style="color:orange">Регистрация: Стъпка 2</h3>
    <div id="in-center">
        <h3>Моля продължете с регистрацията</h3>
        <h3>Моля изберете катедра</h3>
        @Html.Partial("~/Views/Shared/_DepartmentsPartial.cshtml")
        <input type="submit" value="Избери катедра" class="btn btn-info" />
    </div>
}

SearchSystem/Views/CustomRegistration/RegisterProfessor.cshtml
@model SearchSystem.Models.ProfessorWithKeywordsViewModel
@Scripts.Render("~/bundles/jquery")
@Styles.Render("~/Content/UniversitySystem.css")

@using (Html.BeginForm("RegisterProfessor", "CustomRegistration", FormMethod.Post))
{
    //We get selected department from viewbag and put it in professor profile
    Model.Professor.DepartmentName = @ViewBag.departmentName;
    <h3 style="color:orange">Регистрация: Стъпка 3</h3>
    <input type="hidden" value="@Model.Professor.DepartmentName" name="Professor.DepartmentName" />
    <div><p class="editor-label required">Задължителни полета</p></div>
    <table class="table">
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.FirstName)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.FirstName)
                @Html.EditorFor(x => x.Professor.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.LastName)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.LastName)
                @Html.EditorFor(x => x.Professor.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.Subjects)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Subjects)
                @Html.EditorFor(x => x.Professor.Subjects, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.Education)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Education)
                @Html.EditorFor(x => x.Professor.Education, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th>@Html.LabelFor(x => x.Professor.Specialisations)</th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Specialisations)
                @Html.EditorFor(x => x.Professor.Specialisations, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.ProfesionalInterests)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.ProfesionalInterests)
                @Html.EditorFor(x => x.Professor.ProfesionalInterests, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th>@Html.LabelFor(x => x.Professor.AwardsAndHonors)</th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.AwardsAndHonors)
                @Html.EditorFor(x => x.Professor.AwardsAndHonors, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th>@Html.LabelFor(x => x.Professor.Certifications)</th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Certifications)
                @Html.EditorFor(x => x.Professor.Certifications, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th>@Html.LabelFor(x => x.Professor.Patents)</th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Patents)
                @Html.EditorFor(x => x.Professor.Patents, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th>@Html.LabelFor(x => x.Professor.Publications)</th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Publications)
                @Html.EditorFor(x => x.Professor.Publications, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.Email)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Email)
                @Html.EditorFor(x => x.Professor.Email, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.OfficeHours)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.OfficeHours)
                @Html.EditorFor(x => x.Professor.OfficeHours, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
        <tr>
            <th><div class="editor-label required">@Html.LabelFor(x => x.Professor.Phone)</div></th>
            <td>
                @Html.ValidationMessageFor(x => x.Professor.Phone)
                @Html.EditorFor(x => x.Professor.Phone, new { htmlAttributes = new { @class = "form-control" } })
            </td>
        </tr>
    </table>

    @Html.Partial("~/Views/Shared/_KeywordsPartial.cshtml", Model.Keywords);

    <input type="submit" value="Регистрирай" class="btn btn-info" />
}